name: Elegant TW API Push To Main Branch

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Install dependencies
        run: go mod download
      - name: Run Clean Architecture Test
        run: go test -v ./...
